version: "1"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    restart: always

  goapp:
    build: .
    restart: always
    environment:
      - SECRET_KEY=qwertqwertqwertqwertqwertqwertqwert1234
    ports:
      - "8080:8080"
    depends_on:
      - postgres
